name: Balance App GitHub CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run frontend tests
        run: npm test --prefix frontend --coverage --coverageReporters=json:./coverage/frontend-coverage.json

      - name: Run backend tests
        run: npm test --prefix backend --coverage --coverageReporters=json:./coverage/backend-coverage.json

      - name: Generate frontend coverage report
        run: npx istanbul-reports combine -d ./coverage/frontend-report -r html json ./coverage/frontend-coverage.json

      - name: Generate backend coverage report
        run: npx istanbul-reports combine -d ./coverage/backend-report -r html json ./coverage/backend-coverage.json

      - name: Code Coverage Report - Frontend
        uses: actions/upload-artifact@v2
        with:
          name: frontend-coverage
          path: ./coverage/frontend-report

      - name: Code Coverage Report - Backend
        uses: actions/upload-artifact@v2
        with:
          name: backend-coverage
          path: ./coverage/backend-report

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
