name: Balance App GitHub CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: |
          npm run test --prefix frontend -- --coverage
          npm run test --prefix backend -- --coverage

      - name: Generate coverage report
        run: |
          npm install -g istanbul-reports
          npx istanbul-reports combine -d ./coverage -r html

      - name: Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: ./coverage/lcov-report/index.html
  
  deploy_development:
    name: Deploying to the Development environment
    if: github.ref =='refs/heads/main'
    runs-on: ubuntu-latest
    environment: Development
    needs: build

    steps:
    - name: Git clone the repository
      uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} #  TODO need to add this to secrets
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #  TODO need to add this to secrets
        aws-region: us-east-1 # maybe best not to hardcode
    
    - name: Deploying to Development
      run: echo"" # place holder for when we set up place to deploy  
  
  # can add another job to deploy to another env (prod) if needed